/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.passwordkeeper.forms;

import com.passwordkeeper.classes.AlgorithmAES;
import jdk.jfr.Category;
import org.xml.sax.SAXException;

import javax.swing.*;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;

/**
 *
 * @author Cargamoni
 */
public class CreateCategoryFrame extends javax.swing.JFrame {

    /**
     * Creates new form CreateCategoryFrame
     */
    AlgorithmAES FromClass;
    int CategoryNum = -1;
    public CreateCategoryFrame()
    {
        initComponents();
    }

    public CreateCategoryFrame(AlgorithmAES AesClass)
    {
        FromClass = AesClass;
        initComponents();
    }

    public CreateCategoryFrame(AlgorithmAES AesClass, int CategoryID) throws IOException, SAXException, ParserConfigurationException {
        FromClass = AesClass;
        CategoryNum = CategoryID;
        initComponents();
        if(CategoryNum != -1)
            jTextField1.setText(FromClass.CategoryNameReturner(CategoryNum));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();

        setResizable(false);
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        //Kapatıldığında bir önceki forma dönmeyi sağlıyor.
        addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                JFrame frame = (JFrame)e.getSource();
                frame.setVisible(false);
                CategoryFrame newFrame = null;
                try {
                    newFrame = new CategoryFrame(FromClass);
                } catch (ParserConfigurationException parserConfigurationException) {
                    parserConfigurationException.printStackTrace();
                } catch (SAXException saxException) {
                    saxException.printStackTrace();
                } catch (IOException ioException) {
                    ioException.printStackTrace();
                }
                newFrame.setVisible(true);
            }
        });

        jLabel1.setText("Category Name");

        jTextField1.setText("");

        jToggleButton1.setText("Enter");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jToggleButton1(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (SAXException e) {
                    e.printStackTrace();
                } catch (ParserConfigurationException e) {
                    e.printStackTrace();
                } catch (TransformerException e) {
                    e.printStackTrace();
                }
            }});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 305, Short.MAX_VALUE))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();

        //Ekranın ortasında çıkması için
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int xLoc = (dim.width/2-this.getSize().width/2);
        int yLoc = (dim.height/2)-this.getSize().height/2;
        this.setLocation(xLoc,yLoc);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1(java.awt.event.ActionEvent evt) throws IOException, SAXException, ParserConfigurationException, TransformerException {
        if(CategoryNum == -1)
        {
            if(jTextField1.getText().length() != 0)
            {
                FromClass.NewCategoryAdder(jTextField1.getText());
                JOptionPane.showMessageDialog(null, "Category Created", "Success", JOptionPane.INFORMATION_MESSAGE);
                setVisible(false);
                CategoryFrame newFrame = new CategoryFrame(FromClass);
                newFrame.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(null, "Enter a Category Name !", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(jTextField1.getText().length() != 0)
            {
                /// Modify Mode
                FromClass.CategoryModifier(CategoryNum ,jTextField1.getText());
                setVisible(false);
                CategoryFrame newFrame = new CategoryFrame(FromClass);
                newFrame.setVisible(true);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateCategoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateCategoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateCategoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateCategoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateCategoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
