/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.passwordkeeper.forms;

import com.passwordkeeper.classes.AlgorithmAES;
import org.xml.sax.SAXException;

import javax.swing.*;
import javax.xml.parsers.ParserConfigurationException;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Base64;

/**
 *
 * @author Cargamoni
 */
public class PasswordAddModify extends javax.swing.JFrame {

    /**
     * Creates new form PasswordAddModify
     */
    AlgorithmAES FromClass;
    int CategoryNum;
    int PasswordNum = -1;
    String[] PasswordStrings;
    public PasswordAddModify()
    {
        initComponents();
    }

    public PasswordAddModify(AlgorithmAES AesClass , int CategoryID)
    {
        FromClass = AesClass;
        CategoryNum = CategoryID;
        initComponents();
    }

    public PasswordAddModify(AlgorithmAES AesClass , int CategoryID, int PasswordID) throws IOException, SAXException, ParserConfigurationException {
        FromClass = AesClass;
        CategoryNum = CategoryID;
        PasswordNum = PasswordID;
        initComponents();
        PasswordStrings = FromClass.ModifyThisPasswordStrings(CategoryNum,PasswordNum);
        if(PasswordStrings.length > 0)
        {
            //String Pass = String.valueOf(Base64.getDecoder().decode(PasswordStrings[1]));
            String Pass = String.valueOf(PasswordStrings[1]);
            jTextField1.setText(PasswordStrings[0]);
            jPasswordField2.setText(Pass);
            jPasswordField3.setText(Pass);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setResizable(false);
        // Kapatıldığında bir önceki frame'e dönmesini sağlar.
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent e)
            {
                JFrame frame = (JFrame)e.getSource();
                frame.setVisible(false);
                PasswordFrame newFrame = null;
                try {
                    newFrame = new PasswordFrame(FromClass, CategoryNum);
                } catch (ParserConfigurationException parserConfigurationException) {
                    parserConfigurationException.printStackTrace();
                } catch (SAXException saxException) {
                    saxException.printStackTrace();
                } catch (IOException ioException) {
                    ioException.printStackTrace();
                }
                newFrame.setVisible(true);
            }
        });

        jButton1.setText("Add Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                } catch (SAXException e) {
                    e.printStackTrace();
                } catch (ParserConfigurationException e) {
                    e.printStackTrace();
                }
            }});

        jLabel1.setText("Password Name");
        jTextField1.setText("");
        jLabel2.setText("Enter Password");
        jLabel3.setText("Re-Enter Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jPasswordField3)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPasswordField2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();

        //Ekranın ortasında çıkması için
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int xLoc = (dim.width/2-this.getSize().width/2);
        int yLoc = (dim.height/2)-this.getSize().height/2;
        this.setLocation(xLoc,yLoc);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException, SAXException, ParserConfigurationException
    {
        if(PasswordNum == -1)
        {
            /// Password koruması yapılacak
            if(jTextField1.getText().length() != 0)
            {
                if(String.valueOf(jPasswordField2.getPassword()).length() != 0 && String.valueOf(jPasswordField3.getPassword()).length() != 0)
                {
                    if(String.valueOf(jPasswordField3.getPassword()).equals(String.valueOf(jPasswordField2.getPassword())))
                    {
                        FromClass.NewPasswordAdder(CategoryNum, jTextField1.getText(), String.valueOf(jPasswordField2.getPassword()));
                        JOptionPane.showMessageDialog(null, "Password Added !", "Success", JOptionPane.INFORMATION_MESSAGE);
                        CategoryFrame GoBackToCategory = new CategoryFrame(FromClass);
                        setVisible(false);
                        GoBackToCategory.setVisible(true);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Passwords Not Match !", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Enter a Passwords !", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Enter a Password Name !", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            if(jTextField1.getText().length() != 0)
            {
                if(String.valueOf(jPasswordField2.getPassword()).length() != 0 && String.valueOf(jPasswordField3.getPassword()).length() != 0)
                {
                    if(String.valueOf(jPasswordField3.getPassword()).equals(String.valueOf(jPasswordField2.getPassword())))
                    {
                        FromClass.DeleteThisPassword(CategoryNum, PasswordNum);
                        FromClass.NewPasswordAdder(CategoryNum, jTextField1.getText(), String.valueOf(jPasswordField2.getPassword()));
                        JOptionPane.showMessageDialog(null, "Password Added !", "Success", JOptionPane.INFORMATION_MESSAGE);
                        CategoryFrame GoBackToCategory = new CategoryFrame(FromClass);
                        setVisible(false);
                        GoBackToCategory.setVisible(true);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Passwords Not Match !", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Enter a Passwords !", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Enter a Password Name !", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordAddModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordAddModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordAddModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordAddModify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasswordAddModify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
